PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX abcrm: <http://astragale.cnrs.fr/owl/abcrm/>
PREFIX skos:        <http://www.w3.org/2004/02/skos/core#>

SELECT ?bw_uri ?bw_label ?bw_type_uri ?bw_skoslabel
WHERE {
    FILTER NOT EXISTS { ?bw_uri  abcrm:P46i_forms_part_of  [] } 
  	?bw_uri a abcrm:E22_Human_Made_Object ;
      rdfs:label ?bw_label .

    OPTIONAL {
      ?bw_uri abcrmax:Px2_has_type ?bw_type_uri ;
      
      OPTIONAL {
        ?bw_type_uri skos:prefLabel ?bw_skoslabel .
              FILTER (lang(?bw_skoslabel) = 'fr')
      }
    }
} LIMIT 20