PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>
PREFIX abcrm:       <http://astragale.cnrs.fr/owl/abcrm/>
PREFIX abcrmgeo:    <http://astragale.cnrs.fr/owl/abcrmgeo/>
PREFIX abcrmsci:    <http://astragale.cnrs.fr/owl/abcrmsci/>
PREFIX abcrmax:     <http://astragale.cnrs.fr/owl/abcrmax/>
PREFIX dc:          <http://purl.org/dc/elements/1.1/>
SELECT ?geom_path ?file_label ?file_creator ?file_format ?file_date ?scrs_geom_label
WHERE {
    <$geom_uri> abcrmax:Px90_has_value ?geom_path ;
        rdfs:label  ?file_label ;
        dc:creator  ?file_creator ;
        dc:format   ?file_format ;
        dc:date     ?file_date ;
        abcrmax:Qx5_is_defined_in ?sp4 .
    
    ?sp4 rdfs:label ?scrs_geom_label .
}