version: "3"
services:
  oxigraph:
    container_name: oxigraph
    image: ghcr.io/oxigraph/oxigraph:v0.3.19  # ghcr.io/oxigraph/oxigraph:latest
    volumes:
      - ./data-oxigraph:/data
    ## To build from local source code:
    # build:
    #   context: .
    #   dockerfile: server/Dockerfile
    # command:
      # - "oxigraph_server --location /data load --file litho.ttl"  ## v0.2
      # - "oxigraph_server serve --location MY_STORAGE"             ## v0.3
    networks:
      - astraglob
    ports:
      - "7878:7878"
    labels:
      - traefik.enable=true
      - traefik.http.routers.myoxigraph.entrypoints=${TRAEFIK_DEFAULT_SERVICES_ENTRYPOINT}
      - traefik.http.routers.myoxigraph.rule=Host(`oxigraph.${HOST_DOMAIN}`)
      - traefik.http.routers.myoxigraph.service=myoxigraph
      - traefik.http.services.myoxigraph.loadbalancer.server.port=7878

      # - traefik.http.routers.myoxigraph.middlewares=mybasicauth                   # en-ligne/prod

networks:
  astraglob:
    name: astraglob
