PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX acrm: <http://astragale.cnrs.fr/sem/acrm/>
PREFIX acrmex: <http://astragale.cnrs.fr/sem/acrmmex/>
PREFIX acrmsci: <http://astragale.cnrs.fr/sem/acrmsci/>
PREFIX acrmgeo: <http://astragale.cnrs.fr/sem/acrmgeo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
SELECT * 
WHERE {
    ?sub_e22 acrm:P46i_forms_part_of* <$uri_existing_builtwork> ;
    	a acrm:E22_HumanMadeObject ;
        rdfs:label ?sub_e22l .
}