PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ecrm: <http://erlangen-crm.org/170309/>
PREFIX ecrmgeo: <http://erlangen-crm.org/ecrmgeo/>
PREFIX aecrmex: <http://astragale.map.cnrs.fr/sem/aecrmex/>
PREFIX aecrmsci: <http://astragale.map.cnrs.fr/sem/aecrmsci/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT *
WHERE {
    ?s7_sim a aecrmsci:S7_Simulation ;
        rdfs:label ?label ;
        aecrmex:Px2_has_type ?uri_type ; # uri_DEM NSCD, FEM Morenon...
        aecrmex:Qx23_has_value ?data_path ;
        dc:creator ?creator ;
        dc:format ?format ;
        dc:date ?date ;
        ecrm:P7_took_place_at/rdfs:label ?geom_name .
    
    OPTIONAL {
        ?s7_sim aecrmex:Px2_has_type/skos:prefLabel ?type .
    }
}